const { itemNamesToItems } = require('./utils.js');

const DIR_NAMES_TO_SECTION_NAMES = {
  base_npc: "Base NPC",
  mood: "Mood",
  background: "Background",
  torso: "Torso",
  face_slot_1: "Face Slot #1",
  face_slot_2: "Face Slot #2",
  piercings: "Piercings",
  eyewear_glasses: "Eyewear & Glasses",
  hairstyle_hats: "Hairstyle & Hats",
  item: "Item",
}

const DIR_NAMES_ARRAY = Object.keys(DIR_NAMES_TO_SECTION_NAMES)

const SECTION_NAMES_TO_DIR_NAMES = {
  "Base NPC": "base_npc",
  mood: "mood",
  background: "background",
  torso: "torso",
  "faceSlot1": "face_slot_1",
  "faceSlot2": "face_slot_2",
  piercings: "piercings",
  "eyewearAndGlasses": "eyewear_glasses",
  "hairstyleAndHats": "hairstyle_hats",
  item: "item",
}

const BASE_NPC_ITEM_NAMES = ["base npc"]

const MOOD_ITEM_NAMES = ["Neutral", "Angry"]

const BACKGROUND_ITEM_NAMES = [
  "Another One",
  "Backrooms",
  "Bathroom",
  "Bodega",
  "Capitol",
  "Cascadia",
  "Casino",
  "Cherry Blossom",
  "Chicago",
  "Classic Blue",
  "Coffee Shop",
  "Desert",
  "Fancy Interior",
  "Farm",
  "Fast Food",
  "Forest",
  "Garage",
  "Great Plains",
  "Great Wall",
  "Green",
  "Gym",
  "High-End Kitchen",
  "India",
  "Living Room",
  "London",
  "Los Angeles",
  "Medieval",
  "Moon",
  "Nature",
  "Nuke",
  "Outback",
  "Paris",
  "Penthouse",
  "Pub",
  "Pyramids",
  "Red",
  "Rio De Janeiro",
  "Safari",
  "Seoul",
  "Shanghai",
  "Shibuya",
  "Ship",
  "Slots",
  "Smurf Cat's Bag",
  "Southwest",
  "Sproto Wall",
  "Spx",
  "Stock Exchange",
  "Strip Mall",
  "Suburbia",
  "Sudoswap",
  "Supermarket",
  "Taj Mahal",
  "Theater",
  "Times Square",
  "Tropical",
  "Underwater",
  "Wagie",
  "White House",
  "$Wpc HQ",
  "Yellow",
  "$Zoomer",
  "Frenpet",
  "Base",
]

const TORSO_ITEM_NAMES = [
  "Neutral",
  "Armor Torso",
  "Club Kit",
  "Astronaut",
  "Biker",
  "Blouse",
  "Bomber Jacket",
  "Chef",
  "Combat Uniform",
  "Dive Suit",
  "Dress",
  "Farmer",
  "Football Jersey",
  "Hoodie",
  "Lab Coat",
  "Comic Fan",
  "Blue Tshirt",
  "Tennis Shirt",
  "Puffy",
  "Racer",
  "Roman",
  "Rugby Shirt",
  "Samurai",
  "Smurf Bag",
  "$Spx Torso",
  "Barista",
  "Suit",
  "Sundress",
  "Sweater",
  "Undershirt",
  "Western Shirt",
  "White Collar",
  "Tanktop",
  "$Wpc Torso",
]

const FACE_SLOT_1_ITEM_NAMES = [
  "Neutral",
  "Beard",
  "Curly",
  "Fade",
  "Five O'Clock",
  "Grey Beard",
  "Mutton Chops",
  "Patchy",
  "Soul Patch",
  "Sproto",
  "Stache",
  "Viking",
]

const FACE_SLOT_2_ITEM_NAMES = [
  "Neutral",
  "Cigar",
  "Cigarette",
  "Covid Mask",
  "Lipstick",
  "Party Blower",
  "Pipe",
  "Support",
  "Toothpick",
  "Whistle",
]

const PIERCINGS_ITEM_NAMES = [
  "Neutral",
  "Big Hoop",
  "Diamond",
  "Nose Bridge Studs",
  "Septum",
  "Small Earring",
]

const EYEWEAR_GLASSES_ITEM_NAMES = [
  "Neutral",
  "3d Glasses",
  "Black Sunglasses",
  "Blindfold",
  "Circle",
  "Crying",
  "Grandma",
  "Meme Glasses",
  "Monocle",
  "Future",
  "New Year's Eye",
  "Nouns",
  "Novelty",
  "Protective Goggles",
  "Rainbow Shades",
  "Shutter Shades",
  "Sleep",
  "Sunglasses",
  "Swimming Goggles",
  "$Mog",
  "Vr",
]

const HAIRSTYLE_HATS_ITEM_NAMES = [
  "Neutral",
  "Tekashi",
  "Astronaut Helmet",
  "Beanie",
  "Biden",
  "Big Afro",
  "Blonde",
  "Bowie Hat",
  "Bucket Hat",
  "Bun",
  "Chef Hat",
  "Combat Helm",
  "Cowboy Hat",
  "Crown",
  "Diving Helmet",
  "Fedora",
  "Football",
  "Visor",
  "Hijab",
  "Icecreamsogood",
  "Just",
  "Karen",
  "Knight",
  "Maga Hat",
  "Party Hat",
  "Pink",
  "Pompadour",
  "Ponytail",
  "Professional",
  "Propeller Hat",
  "Purple snapback",
  "Redcap",
  "Redsnapback",
  "Roman",
  "Samurai Helmet",
  "Short Sides",
  "One Side Shaved",
  "Smurfhat",
  "Society",
  "Wizard",
  "Spiky",
  "$Spx Hair",
  "Swept",
  "Taper Fade",
  "Top Hat",
  "Waves",
  "$Wpc Hair",
  "Zoomer",
  "Toshi Ears",
]

const ITEM_ITEM_NAMES = [
  "Neutral",
  "Ak47",
  "Android",
  "Baguette",
  "Beer",
  "Big Game",
  "Book",
  "Brewski",
  "Coffee",
  "Duffel Bag",
  "Flip Phone",
  "Football",
  "Guitar",
  "Hand",
  "Ice Cream",
  "Iphone",
  "M4",
  "Martini",
  "Megaphone",
  "Pitchfork",
  "Podcast Mic",
  "Remote",
  "Rpg-7",
  "Shotgun",
  "Silenced Pistol",
  "Spatula",
  "Surfboard",
  "Sword And Shield",
  "Thermos",
]

const DIR_NAMES_TO_ITEM_NAMES = {
  base_npc: BASE_NPC_ITEM_NAMES,
  mood: MOOD_ITEM_NAMES,
  background: BACKGROUND_ITEM_NAMES,
  torso: TORSO_ITEM_NAMES,
  face_slot_1: FACE_SLOT_1_ITEM_NAMES,
  face_slot_2: FACE_SLOT_2_ITEM_NAMES,
  piercings: PIERCINGS_ITEM_NAMES,
  eyewear_glasses: EYEWEAR_GLASSES_ITEM_NAMES,
  hairstyle_hats: HAIRSTYLE_HATS_ITEM_NAMES,
  item: ITEM_ITEM_NAMES,
}

//  const allItems = Object.keys(DIR_NAMES_TO_ITEM_NAMES).map((section) => {
//   return itemNamesToItems(section, DIR_NAMES_TO_ITEM_NAMES[section])
// })

module.exports = {
  DIR_NAMES_TO_SECTION_NAMES,
  DIR_NAMES_ARRAY,
  SECTION_NAMES_TO_DIR_NAMES,
  BASE_NPC_ITEM_NAMES,
  MOOD_ITEM_NAMES,
  BACKGROUND_ITEM_NAMES,
  TORSO_ITEM_NAMES,
  FACE_SLOT_1_ITEM_NAMES,
  FACE_SLOT_2_ITEM_NAMES,
  PIERCINGS_ITEM_NAMES,
  EYEWEAR_GLASSES_ITEM_NAMES,
  HAIRSTYLE_HATS_ITEM_NAMES,
  ITEM_ITEM_NAMES,
  DIR_NAMES_TO_ITEM_NAMES,
  // allItems,
};
